### PR TITLE
Refactor the ack code to break on retry exceptions

### PR DESCRIPTION
**Pull request by venkathangella**
Pull Request type
----

- Bugfix

Changes in this PR
----
- Refactor the ack code to break on retry exceptions
 (This has been missed during the last review comments adressing)

### CODE REVIEW

**Comment by venkathangella** [comment]
@apanicker-nflx please approve this.

**Comment by manan164** [comment]
Hi @panyin99 @aravindanr Can you please review this changes? cc @v1r3n

**Review by felipesilvamelo28 — COMMENTED** [review]
Good luck. I tested here and it worked.
Suggestion:
the pull request could be redone, removing the formatting-only files. there would be only one file left, easier to be approved.

**Comment by venkathangella** [comment]
> Good luck. I tested here and it worked. Suggestion: the pull request could be redone, removing the formatting-only files. there would be only one file left, easier to be approved.

Sure, I will do that.

**Comment by venkathangella** [comment]
@felipesilvamelo28 @manan164, please approve this. I have made the required changes.

**Comment by venkathangella** [comment]
> @felipesilvamelo28 @manan164, please approve this. I have made the required changes.

Please approve the same when you get time.

**Review by felipesilvamelo28 — APPROVED** [review]

**Pull request closed without merging**
