### PR TITLE
Oracle persistence

### PR DESCRIPTION
**Pull request by maheshyaddanapudi**
Release Detail
----

- [x] Feature
- [x] Build related changes
- [x] Other (please describe): Docker / Docker Compose files included.

Feature
--

1. Oracle Persistence / Option to use Oracle Database as persistence unit.
2. Docker Compose example with Oracle Container.

Technical Note
--

1. Utilizes Oracle Database version 11G for Unit Tests 

> Due to GuitHub GI Container disk space limitation, no version > 11G can be used for Unit Tests. 
Can be easily upgraded to 18 XE or 19C Enterprise once GitHub Action updates size capacity which they are apparantly working on).

2. Due to a technical version dependency, spring.flyway.locations cannot be automatically set to db/migration_oracle (similar to postgres-persistence) and **has to be set through .properties file while running the jar along with conductor.db.type**

> Refer to docker/server/config-oracle.properties for example
 
3. Flyway 6.4.4 (5.2+) - Only compatible with Oracle 12.2+
4. Flyway 4.0.3 (<5.2) - Used for Unit Tests as Oracle 11G XE is used for Oracle Container.

### CODE REVIEW

**Comment by CherishSantoshi** [comment]
@v1r3n

**Review by v1r3n — APPROVED** [review]
Can you add a README with required configuration properties and samples?

**Comment by maheshyaddanapudi** [comment]
Properties added to README

**Comment by krishnapyde** [comment]
I was interested to know when this branch will be merged into the main line. Any tentative date?

**Comment by krishnapyde** [comment]
@maheshyaddanapudi would be able to suggest on when this branch would be merged with the Main line? we are very interested in uptake Oracle persistence and are awaiting this code merge. Post which we can go ahead and raise approval requests internally for that version of the conductor.

**Pull request merged**
